server_connect_timeout: 5000
remote_ping_cache: -1
forge_support: false
# Лимит игроков на BungeeCord сервере. -1 = выключено
player_limit: -1
# Права каждой группы пользователей
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  # Значение в МИЛИСЕКУНДАХ! АвтоКик, если клиент не может достучаться до сервера
timeout: 30000
log_commands: false
network_compression_threshold: 256
online_mode: false
disabled_commands:
- disabledcommandhere
# Ваши сервера, подключённые к BungeeCord.
# Заметтье, что порты у всех должны отличатся друг от друга
servers:
# Название сервера
  lobby-[1-3]:
    # Сообщение дня сервера (выводится при переходе на него)
    motd: '&1Just another BungeeCord - Forced Host'
    # IP адрес сервера
    address: localhost:25551
    restricted: false
listeners:
- query_port: 25577
# Сообщение дня сервера (выводится при переходе на него)
# Описание сервера в списке серверов
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - lobby-1
  - lobby-2
  - lobby-3
  bind_local_address: true
  # IP адрес сервера
  host: 0.0.0.0:25577
  # Максимальне количество игроков на обоих серверах (действует только при включённом player_limit)
  max_players: 1
  # Размер таблицы игроков, всплывающей при нажатии TAB (зависит от tab_list)
  tab_size: 60
  # Включить ли при заходе игрока попадание его на fallback_server, независимо от точки отключения?
  force_default_server: false
ip_forward: false
remote_ping_timeout: 5000
prevent_proxy_connections: false
# Группы пользователей
groups:
connection_throttle: 4000
stats: 0fd4d778-93a8-4bf7-af9a-ff764607ce6a
connection_throttle_limit: 3
log_pings: true
